### ISSUE TITLE
How to use multiGPU to train

### ISSUE THREAD

**Issue by YibinLiu666** [senmaoy/RAT-GAN#20]
When I change your code and use `nn.DataParallel` and change `netD.COND_DNET` to `netD.module.COND_DNET` to train， there is an error `RuntimeError: The size of tensor a (24) must match the size of tensor b (48) at non-singleton dimension 0`. Could you tell me how to solve it

**Comment by senmaoy** [comment]
It seems that the batch size is not matched. Could you provide more information about the error

**Comment by YibinLiu666** [comment]
> It seems that the batch size is not matched. Could you provide more information about the error? If you didn't make any changes to the code, the [main_coco.py](https://github.com/senmaoy/RAT-GAN/blob/main/code/main_coco.py) should work well for multi-gpu

The error is at `gates = x_t @ self.W + h_t @ self.U + self.bias` in `DAMSM.py`， I have alse tried `main_coco.py` with no change but there is alse an error `AttributeError: 'DataParallel' object has no attribute 'COND_DNET'`,  so I change `netD.COND_DNET` to `netD.module.COND_DNET`. After I changed it, there is alse the same error 
`Traceback (most recent call last):
  File "main_coco.py", line 308, in <module>
    count = train(dataloader,netG,netD,text_encoder,optimizerG,optimizerD, state_epoch,batch_size,device)
  File "main_coco.py", line 156, in train
    fake = netG(noise,sent_emb)
  File "/home/amax/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/amax/miniconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 171, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/amax/miniconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 181, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/amax/miniconda3/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 89, in parallel_apply
    output.reraise()
  File "/home/amax/miniconda3/lib/python3.7/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/amax/miniconda3/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 64, in _worker
    output = module(*input, **kwargs)
  File "/home/amax/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/amax/zju-nexus-lyb/RAT-GAN/code/model.py", line 35, in forward
    out = self.block0(out,c)
  File "/home/amax/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/amax/zju-nexus-lyb/RAT-GAN/code/model.py", line 83, in forward
    return self.shortcut(x) + self.gamma * self.residual(x, y)
  File "/home/amax/zju-nexus-lyb/RAT-GAN/code/model.py", line 93, in residual
    y,_  =  self.lstm(lstm_input)
  File "/home/amax/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/amax/zju-nexus-lyb/RAT-GAN/code/DAMSM.py", line 167, in forward
    gates = x_t @ self.W + h_t @ self.U + self.bias
RuntimeError: The size of tensor a (12) must match the size of tensor b (24) at non-singleton dimension 0
`

**Comment by senmaoy** [comment]
Hey, I updated the main_coco.py. Can you run it successfully?

**Comment by YibinLiu666** [comment]
> Hey, I updated the main_coco.py. Can you run it successfully?

It returns error that `AttributeError: 'CustomLSTM' object has no attribute 'c_t'`, because you comments the initialization of the `customlstm`. In addition, this error is occurred when I use ` CUDA_VISIBLE_DEVICES=1,2 python main_coco.py --cfg ./cfg/bird.yml`
